server:
  port: 8080
stats-server:
  uri: "${STAT_SERVER_URI:http://localhost:9090}"
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:15432/main-db
    driver-class-name: "org.postgresql.Driver"
    username: "explore"
    password: "secret"