server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request_service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**,/users/{userId}/events/{eventId}/requests/**

        - id: category_service
          uri: lb://category-service
          predicates:
            - Path=/categories/**, /admin/categories/**

        - id: main_service
          uri: lb://main-service
          predicates:
            - Path=/**
#          filters:
#            - PrefixPath=/api/v1
