spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:15432/stats-db
    driver-class-name: "org.postgresql.Driver"
    username: "explore"
    password: "secret"

grpc:
  server:
    port: 0

analyzer:
  user-consumer-properties:
    bootstrap.servers: localhost:9092
    group.id: user.analyzing
    client.id: hubConsumer
    key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
    value.deserializer: ru.practicum.ewm.stats.avro.UserActionDeserializer
    enable.auto.commit: false
  user-topics:
    - stats.user-actions.v1

  similarity-consumer-properties:
    bootstrap.servers: localhost:9092
    group.id: similarity.analyzing
    client.id: snapshotConsumer
    key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
    value.deserializer: ru.practicum.ewm.stats.avro.EventSimilarityDeserializer
    enable.auto.commit: false
  similarity-topics:
    - stats.events-similarity.v1
  consume-attempt-timeout: 1000