server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:15432/stats-db
    driver-class-name: "org.postgresql.Driver"
    username: "explore"
    password: "secret"

#spring:
#  config:
#    activate:
#      on-profile: "test"
#  datasource:
#    url: jdbc:h2:mem:stats-db
#    driver-class-name: "org.h2.Driver"
#    username: "stats-db"
#    password: "secret"
#    url: "jdbc:h2:file:./db/svc_db.mv.db"
#    driverClassName: "org.h2.Driver"
#    username: "svc"
#    password: "qwe123"
#  h2:
#    console:
#      enabled: true